"use strict";
const DIR={up:{name:"Up",symbol:"↑",color:"#4FAF83",key:"ArrowUp"},down:{name:"Down",symbol:"↓",color:"#45AEB5",key:"ArrowDown"},left:{name:"Left",symbol:"←",color:"#9273C8",key:"ArrowLeft"},right:{name:"Right",symbol:"→",color:"#C75C62",key:"ArrowRight"}};
const DEFAULTS={keys:Object.fromEntries(Object.entries(DIR).map(([d,v])=>[d,v.key])),colors:Object.fromEntries(Object.entries(DIR).map(([d,v])=>[d,v.color])),darkArrows:false,sound:true,volume:50,motion:false,motionDefaultV2:true,feedback:true,performance:true};
const DURATION={min:10,max:300,step:5,initial:60}, TRANSITION_MS=400, ARROW_ENTER_MS=220, TOUCH_COOLDOWN_MS=1000, TOUCH_REARM_PAUSE_MS=220, LS="reflex-settings-v1", SS="reflex-session-v1", HIST="reflex-history-v1";
const $=s=>document.querySelector(s), screens=["menu","countdown","game","results"], el=Object.fromEntries(["duration","durationText","count","timer","live","arrow","score","summary","directions","canvas","backdrop","keys","colors","warning"].map(x=>[x,$("#"+x)]));
let settings=load(),state="menu",session,current,readyAt=Infinity,endAt=0,raf,token=0,touch=null,touchReadyAt=0,audioCtx=null,blockedStartKeys=new Set();
function load(){try{let x=JSON.parse(localStorage.getItem(LS));if(x&&!x.motionDefaultV2)x={...x,motion:false,motionDefaultV2:true};return {...structuredClone(DEFAULTS),...(x||{}),keys:{...DEFAULTS.keys,...x?.keys},colors:{...DEFAULTS.colors,...x?.colors}}}catch{return structuredClone(DEFAULTS)}}
function darken(hex,amount=.3){let n=parseInt(hex.slice(1),16),f=1-amount;return `rgb(${Math.round((n>>16)*f)} ${Math.round((n>>8&255)*f)} ${Math.round((n&255)*f)})`}
function applyArrowColor(){if(!current)return;let c=settings.darkArrows?darken(settings.colors[current]):"#fff";document.documentElement.style.setProperty("--arrow-color",c);document.documentElement.style.setProperty("--fx-color",c)}
function save(){localStorage.setItem(LS,JSON.stringify(settings));document.body.classList.toggle("soft",!settings.motion);applyArrowColor()}
function unlockAudio(){if(!settings.sound)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==="suspended")audioCtx.resume()}catch{}}
function softTone(freq,at,duration=.14,volume=.035,type="sine",endFreq=freq){if(!audioCtx||!settings.sound)return;let o=audioCtx.createOscillator(),g=audioCtx.createGain(),f=audioCtx.createBiquadFilter(),level=volume*1.5*(settings.volume/50);o.type=type;o.frequency.setValueAtTime(freq,at);o.frequency.exponentialRampToValueAtTime(Math.max(40,endFreq),at+duration);f.type="lowpass";f.frequency.value=1400;g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(Math.max(.0001,level),at+.025);g.gain.exponentialRampToValueAtTime(.0001,at+duration);o.connect(f).connect(g).connect(audioCtx.destination);o.start(at);o.stop(at+duration+.02)}
function playSound(kind){if(!audioCtx||!settings.sound)return;let t=audioCtx.currentTime+.01;if(kind==="count")softTone(300,t,.09,.018,"sine",340);if(kind==="start"){softTone(360,t,.2,.028,"sine",540);softTone(540,t+.08,.24,.025,"triangle",720)}if(kind==="correct"){softTone(480,t,.16,.032,"sine",680);softTone(720,t+.045,.18,.02,"triangle",860)}if(kind==="wrong"){softTone(210,t,.2,.026,"sine",145);softTone(150,t+.04,.18,.014,"triangle",105)}if(kind==="end"){[392,494,587].forEach((n,i)=>softTone(n,t+i*.07,.38,.018,"sine",n*1.04))}}
function show(id){screens.forEach(x=>$("#"+x).classList.toggle("active",x===id));state=id}
function durationLabel(s){return s<60?`${s} sec`:s%60?`${Math.floor(s/60)} min ${s%60} sec`:`${s/60} min`}
function updateDuration(){let v=+el.duration.value;el.durationText.value=durationLabel(v);el.duration.style.setProperty("--range",`${(v-DURATION.min)/(DURATION.max-DURATION.min)*100}%`)}
function keyLabel(k){return {ArrowUp:"↑",ArrowDown:"↓",ArrowLeft:"←",ArrowRight:"→",Space:"Space"}[k]||k.replace(/^(Key|Digit)/,"")}
function countdown(){if(state!=="menu"&&state!=="results")return;unlockAudio();closeSettings();show("countdown");let values=["3","2","1","GO!"],hints=["GET READY","FOCUS","BREATHE","GO!"],i=0;function next(){el.count.textContent=values[i];$("#countHint").textContent=hints[i];playSound(i===3?"start":"count");i++;el.count.className="";void el.count.offsetWidth;el.count.className="count-animate";if(i<values.length)setTimeout(next,i===3?700:760);else setTimeout(start,620)}next()}
function start(){let duration=+el.duration.value;touch=null;touchReadyAt=performance.now()+TOUCH_COOLDOWN_MS;readyAt=Infinity;session={duration,startTime:new Date().toISOString(),endTime:null,correct:0,errors:0,rounds:[]};sessionStorage.setItem(SS,JSON.stringify({...session,interrupted:true}));endAt=performance.now()+duration*1000;show("game");el.live.hidden=!settings.performance;nextArrow(true);raf=requestAnimationFrame(tick)}
function tick(now){let remain=Math.max(0,endAt-now);el.timer.textContent=`${Math.floor(remain/60000)}:${String(Math.ceil(remain/1000)%60).padStart(2,"0")}`;if(remain<=0)return finish();raf=requestAnimationFrame(tick)}
function restartClass(node,name){node.className="";void node.offsetWidth;node.className=name}
function burst(correct){let pop=$("#feedbackPop"),pulse=$("#bgPulse"),shell=$("#arrowShell");pop.textContent=correct?"NICE!":"MISS −1";restartClass(pop,correct?"good-pop":"bad-pop");restartClass(pulse,correct?"bg-pulse success":"bg-pulse fail");restartClass(shell,correct?"shell-success":"shell-fail");if(correct){let box=$("#particles");box.innerHTML="";for(let i=0;i<12;i++){let p=document.createElement("i");p.style.setProperty("--a",`${i*30}deg`);p.style.setProperty("--delay",`${(i%3)*18}ms`);box.append(p)}}}
function nextArrow(first=false){let mine=++token,ds=Object.keys(DIR),d=ds[Math.floor(Math.random()*4)],game=$("#game"),wash=$("#colorWash"),shell=$("#arrowShell");readyAt=Infinity;if(first){shell.className="";current=d;game.style.backgroundColor=settings.colors[d];applyArrowColor();el.arrow.dataset.dir=d;el.arrow.setAttribute("aria-label",`${DIR[d].name} arrow`);el.arrow.className="enter";setTimeout(()=>{if(mine===token&&state==="game"){el.arrow.className="";readyAt=performance.now()}},ARROW_ENTER_MS);return}el.arrow.className="hit";wash.style.setProperty("--next-bg",settings.colors[d]);restartClass(wash,"color-wash active");setTimeout(()=>{if(mine!==token||state!=="game")return;shell.className="";game.style.backgroundColor=settings.colors[d];current=d;applyArrowColor();el.arrow.dataset.dir=d;el.arrow.setAttribute("aria-label",`${DIR[d].name} arrow`);el.arrow.className="enter";wash.className="color-wash";setTimeout(()=>{if(mine===token&&state==="game"){el.arrow.className="";readyAt=performance.now()}},ARROW_ENTER_MS)},TRANSITION_MS)}
function gameInput(code,source="keyboard"){if(state!=="game"||!Object.values(settings.keys).includes(code))return;if(performance.now()>=endAt)return finish();let pressed=Object.entries(settings.keys).find(([,k])=>k===code)?.[0];if(pressed===current&&performance.now()>=readyAt){let now=performance.now(),reaction=now-readyAt;session.correct++;session.rounds.push({round:session.correct,direction:current,key:source==="touch"?`Swipe${DIR[pressed].name}`:code,reactionMs:+reaction.toFixed(2),elapsedMs:+(now-(endAt-session.duration*1000)).toFixed(2)});persist();el.live.textContent=`${session.correct-session.errors} pts · ${Math.round(reaction)} ms`;playSound("correct");if(settings.motion)burst(true);nextArrow()}else if(pressed!==current){session.errors++;persist();el.live.textContent=`${session.correct-session.errors} pts · ${session.errors} misses`;playSound("wrong");if(settings.feedback){restartClass(el.arrow,"error");burst(false)}}}
function gameKey(e){if(e.repeat||!Object.values(settings.keys).includes(e.code))return;e.preventDefault();gameInput(e.code)}
function persist(){sessionStorage.setItem(SS,JSON.stringify({...session,interrupted:true}))}
function calc(v){if(!v.length)return{avg:0,median:0,best:0,worst:0};let s=[...v].sort((a,b)=>a-b);return{avg:v.reduce((a,b)=>a+b)/v.length,median:s.length%2?s[(s.length-1)/2]:(s[s.length/2-1]+s[s.length/2])/2,best:s[0],worst:s.at(-1)}}
function finish(){if(state!=="game")return;cancelAnimationFrame(raf);token++;playSound("end");session.endTime=new Date().toISOString();let s=calc(session.rounds.map(x=>x.reactionMs)),attempts=session.correct+session.errors;session.summary={...s,accuracy:attempts?session.correct/attempts*100:0,rpm:session.correct/session.duration*60,score:session.correct-session.errors};sessionStorage.setItem(SS,JSON.stringify({...session,interrupted:false}));let h=[];try{h=JSON.parse(sessionStorage.getItem(HIST)||"[]")}catch{}h.push(session);sessionStorage.setItem(HIST,JSON.stringify(h.slice(-20)));render();show("results")}
const ms=v=>v?`${Math.round(v)} ms`:"—";
function render(){let s=session.summary;el.score.textContent=s.score;let a=[[session.correct,"Correct"],[session.errors,"Misses (−1 each)"],[s.accuracy.toFixed(1)+"%","Accuracy"],[ms(s.avg),"Average"],[ms(s.median),"Median"],[ms(s.best),"Best"],[ms(s.worst),"Worst"],[s.rpm.toFixed(1),"Per minute"]];el.summary.innerHTML=a.map(([v,n])=>`<div class="stat"><strong>${v}</strong><span>${n}</span></div>`).join("");el.directions.innerHTML=Object.keys(DIR).map(d=>{let r=session.rounds.filter(x=>x.direction===d),s=calc(r.map(x=>x.reactionMs));return `<div class="stat"><strong><i class="dot" style="background:${settings.colors[d]}"></i>${r.length}</strong><span>${DIR[d].name} · ${ms(s.avg)}</span></div>`}).join("");requestAnimationFrame(chart)}
function chart(){let c=el.canvas,r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2),x=c.getContext("2d"),v=session.rounds.map(q=>q.reactionMs),p=16;c.width=r.width*d;c.height=r.height*d;x.scale(d,d);x.strokeStyle="#ffffff18";for(let i=0;i<4;i++){let y=p+(r.height-2*p)*i/3;x.beginPath();x.moveTo(p,y);x.lineTo(r.width-p,y);x.stroke()}if(v.length<2)return;let max=Math.max(...v,500),min=Math.min(...v,100);x.strokeStyle="#f2f2ef";x.lineWidth=2;x.beginPath();v.forEach((n,i)=>{let px=p+i*(r.width-2*p)/(v.length-1),py=p+(max-n)/(max-min||1)*(r.height-2*p);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}
function renderSettings(){el.keys.innerHTML=el.colors.innerHTML="";Object.keys(DIR).forEach(d=>{el.keys.insertAdjacentHTML("beforeend",`<label class="row"><span>${DIR[d].name}</span><input class="key" data-dir="${d}" readonly value="${keyLabel(settings.keys[d])}"></label>`);el.colors.insertAdjacentHTML("beforeend",`<div class="row"><label>${DIR[d].name}</label><input class="picker" data-dir="${d}" type="color" value="${settings.colors[d]}"><input class="hex" data-dir="${d}" maxlength="7" value="${settings.colors[d].toUpperCase()}"></div>`) });["darkArrows","sound","motion","feedback","performance"].forEach(k=>$("#"+k).checked=settings[k]);$("#volume").value=settings.volume;$("#volume").style.setProperty("--range",`${settings.volume}%`);$("#volumeText").value=`${settings.volume}%`}
function openSettings(){if(state!=="menu")return;renderSettings();el.backdrop.hidden=false;$("#close").focus()}function closeSettings(){el.backdrop.hidden=true}
document.addEventListener("keydown",e=>{if(!el.backdrop.hidden){if(e.key==="Escape")closeSettings();let i=e.target.closest(".key");if(i&&!['Tab','Escape'].includes(e.key)){e.preventDefault();let d=i.dataset.dir,dup=Object.entries(settings.keys).some(([q,k])=>q!==d&&k===e.code);el.warning.hidden=!dup;if(!dup){settings.keys[d]=e.code;i.value=keyLabel(e.code);save();i.blur()}}return}if(state==="menu"&&Object.values(settings.keys).includes(e.code)&&!e.repeat){e.preventDefault();blockedStartKeys.add(e.code);countdown()}else if(!blockedStartKeys.has(e.code))gameKey(e)});document.addEventListener("keyup",e=>blockedStartKeys.delete(e.code));window.addEventListener("blur",()=>blockedStartKeys.clear());
$("#motion").closest("label").insertAdjacentHTML("beforebegin",'<label class="toggle">Soft sound feedback<input id="sound" type="checkbox"><i></i></label><div class="volume-row"><label for="volume">Volume <output id="volumeText">50%</output></label><input id="volume" type="range" min="0" max="100" step="5" value="50"></div>');el.duration.min=DURATION.min;el.duration.max=DURATION.max;el.duration.step=DURATION.step;el.duration.value=DURATION.initial;el.duration.oninput=updateDuration;$("#touchStart").onclick=countdown;$("#open").onclick=openSettings;$("#close").onclick=closeSettings;el.backdrop.onmousedown=e=>{if(e.target===el.backdrop)closeSettings()};$("#resetKeys").onclick=()=>{settings.keys={...DEFAULTS.keys};save();renderSettings()};$("#resetColors").onclick=()=>{settings.colors={...DEFAULTS.colors};save();renderSettings()};$("#resetAll").onclick=()=>{settings=structuredClone(DEFAULTS);save();renderSettings()};el.colors.oninput=e=>{let d=e.target.dataset.dir;if(!d)return;if(e.target.type==="color"){settings.colors[d]=e.target.value;save();renderSettings()}else if(/^#[0-9a-f]{6}$/i.test(e.target.value)){settings.colors[d]=e.target.value;save();e.target.previousElementSibling.value=e.target.value}};["darkArrows","sound","motion","feedback","performance"].forEach(k=>$("#"+k).onchange=e=>{settings[k]=e.target.checked;if(k==="sound"&&e.target.checked)unlockAudio();save()});$("#volume").oninput=e=>{settings.volume=+e.target.value;$("#volumeText").value=`${settings.volume}%`;save()};$("#replay").onclick=countdown;$("#back").onclick=()=>show("menu");window.onresize=()=>state==="results"&&chart();let ct;document.onmousemove=()=>{if(state==="game"){$("#game").classList.add("cursor");clearTimeout(ct);ct=setTimeout(()=>$("#game").classList.remove("cursor"),1400)}};
$("#game").addEventListener("pointerdown",e=>{if(e.pointerType==="mouse"||state!=="game")return;e.preventDefault();touch={id:e.pointerId,x:e.clientX,y:e.clientY,lastDir:null,lastMoveAt:performance.now()};touchReadyAt=0;$("#game").setPointerCapture?.(e.pointerId)});$("#game").addEventListener("pointermove",e=>{if(!touch||touch.id!==e.pointerId||state!=="game")return;e.preventDefault();let now=performance.now(),paused=now-touch.lastMoveAt>TOUCH_REARM_PAUSE_MS,dx=e.clientX-touch.x,dy=e.clientY-touch.y,threshold=Math.max(34,Math.min(innerWidth,innerHeight)*.055);touch.lastMoveAt=now;if(paused)touch.lastDir=null;if(Math.max(Math.abs(dx),Math.abs(dy))<threshold)return;let dir=Math.abs(dx)>Math.abs(dy)?(dx>0?"right":"left"):(dy>0?"down":"up");touch.x=e.clientX;touch.y=e.clientY;if(now<touchReadyAt||dir===touch.lastDir)return;touch.lastDir=dir;touchReadyAt=now+TOUCH_COOLDOWN_MS;gameInput(settings.keys[dir],"touch")});for(const type of ["pointerup","pointercancel","lostpointercapture"])$("#game").addEventListener(type,e=>{if(touch?.id===e.pointerId)touch=null});
$("#volume").addEventListener("input",e=>{let value=+e.target.value;e.target.style.setProperty("--range",`${value}%`);$("#volumeText").value=`${value}%`});save();updateDuration();try{let old=JSON.parse(sessionStorage.getItem(SS));if(old?.interrupted)sessionStorage.setItem(SS,JSON.stringify({...old,interrupted:false,recoveredAt:new Date().toISOString()}))}catch{}
